### ISSUE TITLE
Readme Link to Discord Doesn't Work

### ISSUE THREAD

**Issue by ddewar** [2kai2kai2/eu4img#25]
Hi,

Not sure if you're still working on this project, but I was going to give it a try, but it looks like the link to ask for a bot link is broken. Intentional? If not, would love to see if I can get this to work for my savegame!

**Comment by 2kai2kai2** [comment]
Hi, the link should be fixed now.
I don't work on this project much, but I did recently update and fix issues relating to it, so it should be running fine for now.
